#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../headers/TARVBP.h"
#include "../headers/utils.h"
#include "../headers/TJ.h"
#include "../headers/TABSELE.h"
#include "../headers/operacoes.h"
#include "../headers/TLSE_TJ.h"
#include "../headers/TLSE_CHAR.h"
#include "../headers/operacoes.h"
#include "../headers/TH.h"
